VIA_ENABLE = yes

DYNAMIC_MACRO_ENABLE = yes

AUDIO_ENABLE = no
ENCODER_ENABLE = no

# Set "no" to reduce firmware size.
# CONSOLE_ENABLE = no
# COMMAND_ENABLE = no
# MOUSEKEY_ENABLE = no
# EXTRAKEY_ENABLE = no
# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = no
# MAGIC_ENABLE = no

# --- RGB Matrix ---
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
