VIA_ENABLE = yes

DYNAMIC_MACRO_ENABLE = yes

ENCODER_ENABLE = yes

# Set "no" to reduce firmware size.
# CONSOLE_ENABLE = no
# COMMAND_ENABLE = no
# MOUSEKEY_ENABLE = no
# EXTRAKEY_ENABLE = no
# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = no
# MAGIC_ENABLE = no
